name: build

on:
  push:
    branches: [main]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Debugging
        run: |
          echo 'hello'
